services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd:/app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_AUTH_URL=http://localhost:4000/api/auth
    depends_on:
      - backend
      - auth

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app
      - REDIS_URL=redis://redis:6379/0
      - AUTH_SERVICE_URL=http://auth:4000/api/auth
      - BETTER_AUTH_CLIENT_ID=backend-service
      - BETTER_AUTH_CLIENT_SECRET=backend-service-secret
      - SECRET_KEY=development-secret-key
    depends_on:
      - postgres
      - redis
      - auth

  auth:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "4000:4000"
    volumes:
      - ./Auth:/app
    environment:
      - NODE_ENV=development
      - PORT=4000
      - JWT_SECRET=development-jwt-secret
      - JWT_ACCESS_EXPIRATION=15m
      - JWT_REFRESH_EXPIRATION=7d
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:3000
      - LOGIN_RATE_LIMIT_WINDOW=15
      - LOGIN_RATE_LIMIT_MAX=5
      - BETTER_AUTH_SECRET=better-auth-development-secret
      - BETTER_AUTH_URL=http://localhost:4000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
