services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: [ db-data:/var/lib/postgresql/data ]

  redis:
    image: redis:7-alpine

  auth-service:
    image: myregistry.azurecr.io/betterauth:${TAG}
    ports: ["4000:4000"]
    depends_on: [db]

  backend:
    image: myregistry.azurecr.io/myapp-backend:${TAG}
    ports: ["8000:8000"]
    depends_on: [db, redis, auth-service]

  frontend:
    image: myregistry.azurecr.io/myapp-frontend:${TAG}
    ports: ["80:80"]
    depends_on: [auth-service, backend]

volumes:
  db-data: