services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: myapp_dev
    volumes: [ db-data:/var/lib/postgresql/data ]

  redis:
    image: redis:7-alpine

  auth-service:
    build: ./auth-service
    env_file: .env
    ports: ["4000:4000"]
    depends_on: [db]

  backend:
    build: ./backend
    env_file: .env
    ports: ["8001:8000"]     # exposed port 8000 ➔ host 8001
    depends_on: [db, redis, auth-service]

  frontend:
    build: ./frontend
    env_file: .env
    ports: ["3001:80"]       # Nginx port 80 ➔ host 3001
    depends_on: [auth-service, backend]

volumes:
  db-data: