version: '3.8'
services:
  auth-service:
    image: ${ACR_LOGIN_SERVER}/auth-service:${IMAGE_TAG}
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_GITHUB_CLIENT_ID=${BETTER_AUTH_GITHUB_CLIENT_ID}
      - BETTER_AUTH_GITHUB_CLIENT_SECRET=${BETTER_AUTH_GITHUB_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    
  backend:
    image: ${ACR_LOGIN_SERVER}/backend:${IMAGE_TAG}
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    
  frontend:
    image: ${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG}
    restart: always